"""empty message

Revision ID: a8e5fe2c8045
Revises: 9a1dd307305d
Create Date: 2020-10-02 11:00:57.536281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e5fe2c8045'
down_revision = '9a1dd307305d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_lists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('todo_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todo_lists', ['todo_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'todo_list_id')
    op.drop_table('todo_lists')
    # ### end Alembic commands ###
