"""empty message

Revision ID: ed2add03eaca
Revises: a8e5fe2c8045
Create Date: 2020-10-02 11:11:53.360242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2add03eaca'
down_revision = 'a8e5fe2c8045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_lists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('todos', 'todo_list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todo_list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todo_lists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
